# # Default values for webapp-chart

# # Replica count for the application
# replicaCount: ""

# # Image details for the application and flyway migration
# image:
#   repository: ""
#   flywayRepository: ""
#   flywayTag: ""
#   pullPolicy: ""
#   tag: ""

# # Service details for the application
# service:
#   type: ""
#   port: ""

# # Target port on which the application is running
# application:
#   port: ""
#   environtment: ""

# # Deployment strategies to be followed
# deploymentStrategy:
#   type: ""
#   rollingUpdate:
#     maxSurge: ""
#     maxUnavailable: ""
#   minReadySeconds: ""
#   progressDeadlineSeconds: ""

# configMapName: "webapp-configmap"

# # Override the values of subchart
# postgresql:
#   enabled: true
#   auth:
#     username: ""
#     password: ""
#     database: ""

# # Schema used for the application
# postgres:
#   schema: ""
#   port: ""

#   primary:
#     persistence:
#       enabled: true
#       size: ""
#       storageClass: ""
#       accessMode: ""


# Default values for webapp-chart

# Replica count for the application
replicaCount: 1

# Image details for the application and flyway migration
image:
  repository: quay.io/csye-7125/webapp
  flywayRepository: quay.io/csye-7125/webapp-db
  flywayTag: 1.0.1
  pullPolicy: IfNotPresent
  tag: 2.2.0

# Service details for the application
service:
  type: LoadBalancer
  port: 8082

serviceAccount:
  create: true

# Target port on which the application is running
application:
  port: 8080
  environtment: dev

# Deployment strategies to be followed
deploymentStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  minReadySeconds: 30
  progressDeadlineSeconds: 180

configMapName: webapp-config

# Override the values of subchart
postgresql:
  enabled: true
  auth:
    username: csye7125
    password: postgres
    database: app

  primary:
    persistence:
      enabled: true
      size: 8Gi
      storageClass: standard
      accessMode: ReadWriteOnce

# Schema used for the application
postgres:
  schema: app
  port: 5432

operatorNamespace: webapp-operator-system