apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  namespace: {{ if .Values.namespace.create }}{{ .Values.namespace.name }}{{ else }}{{ .Release.Namespace }}{{ end }}
data:
  PORT: "{{ .Values.application.port }}"
  DB_PORT: "{{ .Values.postgres.port }}"
  DB_HOSTNAME: {{ .Release.Name }}-postgresql
  DB_DBNAME: "{{ .Values.postgresql.auth.database }}"
  DB_USERNAME: "{{ .Values.postgresql.auth.username }}"
  DB_PASSWORD: "{{ .Values.postgresql.auth.password }}"
  DB_SCHEMA: "{{ .Values.postgres.schema }}"
  ENVIRONMENT: "{{ .Values.application.environment }}"
  CR_NAMESPACE: "{{ .Values.operatorNamespace }}"