apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    name: {{ .Release.Name }}-network-policy
    namespace: {{ .Release.Namespace }}
spec:
    podSelector:
        matchLabels:
            statefulset.kubernetes.io/pod-name: {{ .Release.Name }}-postgresql-0
    ingress:
    - from:
        - podSelector:
            matchLabels:
                app: {{ .Release.Name }}
      ports:
      - protocol: TCP
        port: 5432
    policyTypes:
    - Ingress