apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway
  namespace:  {{ if .Values.namespace.create }}{{ .Values.namespace.name }}{{ else }}{{ .Release.Namespace }}{{ end }}
spec:
  selector:
    istio: ingressgateway
    app: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol:  HTTP
      hosts:
        - "*"