apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "webapp-chart.fullname" . }}-LimitRange
spec:
  limits:
  - type: Container
    default:
      memory: "256Mi"
      cpu: "250m"
    defaultRequest:
      memory: "128Mi"
      cpu: "125m"
    max:
      memory: "1280Mi"    
      cpu: "1250m"      
    maxLimitRequestRatio:
      memory: "4"
      cpu: "4"
