apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-httpcheck-rolebinding
  namespace: {{ .Values.operatorNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-httpcheck-role
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-serviceaccount
  namespace: {{ .Release.Namespace }}