apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-httpcheck-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - csye7125-fall2023-group07.operator.souvikdinda.me
  resources:
  - httpchecks
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
