name: Chart Validation
on:
    pull_request:
        branches: [ main ]

jobs:
    build:
        name: chart-validation
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: Setup Helm
            uses: azure/setup-helm@v1
            with:
              version: '3'
          
          - name: Lint Chart
            run: helm lint .

          - name: Validate Chart Template Chart
            run: helm template .